opt1 = """
        ************* [ESTUDANTES] MENU DE OPERAÇÕES ************* """
opt2 = """
        ************* [PROFESSORES] MENU DE OPERAÇÕES ************* """
opt3 = """
        ************* [DISCIPLINA] MENU DE OPERAÇÕES ************* """
opt4 = """
        ************* [TURMAS] MENU DE OPERAÇÕES ************* """
opt5 = """
        ************* [MATRICULAS] MENU DE OPERAÇÕES ************* """
opt9 = "====== VOLTAR AO MENU PRINCIPAL ======"
